//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.11 at 05:51:15 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nicl.duke.edu/orca/manage/services/serveractor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package orca.manage.proxies.soap.beans.serveractor;
