//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:21 PM EDT 
//


package orca.manage.proxies.soap.beans.clientactor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import orca.manage.beans.AuthTokenMng;
import orca.manage.beans.PropertiesMng;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="auth" type="{http://www.nicl.duke.edu/orca/manage/beans}authTokenMng"/>
 *         &lt;element name="reservationID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="newUnits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="newResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestProperties" type="{http://www.nicl.duke.edu/orca/manage/beans}propertiesMng"/>
 *         &lt;element name="configProperties" type="{http://www.nicl.duke.edu/orca/manage/beans}propertiesMng"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guid",
    "auth",
    "reservationID",
    "endTime",
    "newUnits",
    "newResourceType",
    "requestProperties",
    "configProperties"
})
@XmlRootElement(name = "ExtendReservationRequest")
public class ExtendReservationRequest {

    @XmlElement(required = true)
    protected String guid;
    @XmlElement(required = true)
    protected AuthTokenMng auth;
    @XmlElement(required = true)
    protected String reservationID;
    protected long endTime;
    @XmlElement(defaultValue = "-1")
    protected int newUnits;
    @XmlElement(required = true)
    protected String newResourceType;
    @XmlElement(required = true)
    protected PropertiesMng requestProperties;
    @XmlElement(required = true)
    protected PropertiesMng configProperties;

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the auth property.
     * 
     * @return
     *     possible object is
     *     {@link AuthTokenMng }
     *     
     */
    public AuthTokenMng getAuth() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthTokenMng }
     *     
     */
    public void setAuth(AuthTokenMng value) {
        this.auth = value;
    }

    /**
     * Gets the value of the reservationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationID() {
        return reservationID;
    }

    /**
     * Sets the value of the reservationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationID(String value) {
        this.reservationID = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     */
    public long getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     */
    public void setEndTime(long value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the newUnits property.
     * 
     */
    public int getNewUnits() {
        return newUnits;
    }

    /**
     * Sets the value of the newUnits property.
     * 
     */
    public void setNewUnits(int value) {
        this.newUnits = value;
    }

    /**
     * Gets the value of the newResourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewResourceType() {
        return newResourceType;
    }

    /**
     * Sets the value of the newResourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewResourceType(String value) {
        this.newResourceType = value;
    }

    /**
     * Gets the value of the requestProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesMng }
     *     
     */
    public PropertiesMng getRequestProperties() {
        return requestProperties;
    }

    /**
     * Sets the value of the requestProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesMng }
     *     
     */
    public void setRequestProperties(PropertiesMng value) {
        this.requestProperties = value;
    }

    /**
     * Gets the value of the configProperties property.
     * 
     * @return
     *     possible object is
     *     {@link PropertiesMng }
     *     
     */
    public PropertiesMng getConfigProperties() {
        return configProperties;
    }

    /**
     * Sets the value of the configProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertiesMng }
     *     
     */
    public void setConfigProperties(PropertiesMng value) {
        this.configProperties = value;
    }

}
