//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:21 PM EDT 
//


package orca.manage.proxies.soap.beans.clientactor;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.manage.proxies.soap.beans.clientactor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.manage.proxies.soap.beans.clientactor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddReservationsRequest }
     * @return created instance
     */
    public AddReservationsRequest createAddReservationsRequest() {
        return new AddReservationsRequest();
    }

    /**
     * Create an instance of {@link ClaimResourcesResponse }
     * 
     * @return created instance
     */
    public ClaimResourcesResponse createClaimResourcesResponse() {
        return new ClaimResourcesResponse();
    }

    /**
     * Create an instance of {@link GetPoolInfoResponse }
     * 
     * @return created instance
     */
    public GetPoolInfoResponse createGetPoolInfoResponse() {
        return new GetPoolInfoResponse();
    }

    /**
     * Create an instance of {@link GetBrokersRequest }
     * @return created instance
     * 
     */
    public GetBrokersRequest createGetBrokersRequest() {
        return new GetBrokersRequest();
    }

    /**
     * Create an instance of {@link GetBrokerRequest }
     * 
     * @return created instance
     */
    public GetBrokerRequest createGetBrokerRequest() {
        return new GetBrokerRequest();
    }

    /**
     * Create an instance of {@link DemandReservationsResponse }
     * 
     * @return created instance
     */
    public DemandReservationsResponse createDemandReservationsResponse() {
        return new DemandReservationsResponse();
    }

    /**
     * Create an instance of {@link GetPoolInfoRequest }
     * 
     * @return created instance
     */
    public GetPoolInfoRequest createGetPoolInfoRequest() {
        return new GetPoolInfoRequest();
    }

    /**
     * Create an instance of {@link DemandReservationRequest }
     * 
     * @return created instance
     */
    public DemandReservationRequest createDemandReservationRequest() {
        return new DemandReservationRequest();
    }

    /**
     * Create an instance of {@link AddReservationRequest }
     * 
     * @return created instance
     */
    public AddReservationRequest createAddReservationRequest() {
        return new AddReservationRequest();
    }

    /**
     * Create an instance of {@link DemandReservationsRequest }
     * 
     * @return created instance
     */
    public DemandReservationsRequest createDemandReservationsRequest() {
        return new DemandReservationsRequest();
    }

    /**
     * Create an instance of {@link GetBrokerResponse }
     * 
     * @return created instance
     */
    public GetBrokerResponse createGetBrokerResponse() {
        return new GetBrokerResponse();
    }

    /**
     * Create an instance of {@link ClaimResourcesRequest }
     * 
     * @return created instance
     */
    public ClaimResourcesRequest createClaimResourcesRequest() {
        return new ClaimResourcesRequest();
    }

    /**
     * Create an instance of {@link DemandReservationResponse }
     * 
     * @return created instance
     */
    public DemandReservationResponse createDemandReservationResponse() {
        return new DemandReservationResponse();
    }

    /**
     * Create an instance of {@link ExtendReservationResponse }
     * 
     * @return created instance
     */
    public ExtendReservationResponse createExtendReservationResponse() {
        return new ExtendReservationResponse();
    }

    /**
     * Create an instance of {@link AddReservationsResponse }
     * @return created instance
     * 
     */
    public AddReservationsResponse createAddReservationsResponse() {
        return new AddReservationsResponse();
    }

    /**
     * Create an instance of {@link AddBrokerRequest }
     * 
     * @return created instance
     */
    public AddBrokerRequest createAddBrokerRequest() {
        return new AddBrokerRequest();
    }

    /**
     * Create an instance of {@link AddBrokerResponse }
     * 
     * @return created instance
     */
    public AddBrokerResponse createAddBrokerResponse() {
        return new AddBrokerResponse();
    }

    /**
     * Create an instance of {@link GetBrokersResponse }
     * 
     * @return created instance
     */
    public GetBrokersResponse createGetBrokersResponse() {
        return new GetBrokersResponse();
    }

    /**
     * Create an instance of {@link ExtendReservationRequest }
     * 
     * @return created instance
     */
    public ExtendReservationRequest createExtendReservationRequest() {
        return new ExtendReservationRequest();
    }

    /**
     * Create an instance of {@link AddReservationResponse }
     * 
     * @return created instance
     */
    public AddReservationResponse createAddReservationResponse() {
        return new AddReservationResponse();
    }

}
