#!/usr/bin/env python
import os
import sys
import logging as LOG
import logging.handlers
import traceback

sys.path.append(os.environ['SLURM_MANAGE_HOME'])

try:
    sys.path.append(os.environ['SLURM_MANAGE_HOME'])
    from slurm_common import *
except:
    print ('Error in slurm-jobnodeinfo: cannot import slurm_common.py')
    sys.exit(1)

try:
    LOG.basicConfig(level=LOG.DEBUG, filename='/tmp/foo')
    # DO the WORK
    data_stdout=SLURM_MANAGE.get_nodestatus(os.environ['SLURM_NODENAME'])

    if str(data_stdout) == 'FALSE' :
	print ('FALSE')
	sys.exit(1)

    print (data_stdout)
    #print 'OK'

except Exception as e:
    print ('FALSE')
    sys.exit(1)

sys.exit(0)
