#!/bin/bash
# chkconfig: 345 15 10
# description: Orca Node Agent
### BEGIN INIT INFO
# Provides:          orca-nodeagent
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Orca Node Agent
### END INIT INFO

export NA_HOME=/opt/orca/nodeagent
export PORT=6
export ORCA_AXIS2_TOOLS_PID_FILE=${NA_HOME}/bin/pid
export PATH=$NA_HOME/bin:${PATH}

case "$1" in
    start)
        if [ -f ${ORCA_AXIS2_TOOLS_PID_FILE} ]; then
           echo "Node Agent service is already running"
        else
           echo "Starting the Node Agent service" 
           cd ${NA_HOME}
           ./bin/http-server.sh repository ${PORT}
           if [ $? -eq 0 ]; then
             echo "Node Agent service started"
             exit 0
           else
             echo "An error occurred while starting the Node Agent service"
             exit -1
           fi
        fi
         ;;
    stop)
        if [ -f ${ORCA_AXIS2_TOOLS_PID_FILE} ]; then
           echo "Stopping the Node Agent service"
           kill -9 `cat ${ORCA_AXIS2_TOOLS_PID_FILE}`
           echo "Node Agent service stopped"           
        else
           echo "Node Agent service is not running"
        fi
        exit 0;        
        ;;
    restart)
    	$0 stop
    	$0 start
    	;;
    *)
        echo "Usage: /etc/init.d/orca-nodeagent {start|stop|restart}"
        exit 1 
        ;;
esac

exit 0

