//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.09 at 08:54:33 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://issg.cs.duke.edu/shirako/manage/extensions/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package orca.extensions.beans;
