#!/usr/bin/env python
import os
import sys
import logging as LOG
import logging.handlers
import traceback

from lockfile import FileLock

sys.path.append(os.environ['IBM_DS_DIR'] + "/scripts")

try:
    sys.path.append(os.environ['IBM_DS_DIR'] + "/scripts")
    from ibm_ds_common import *
except:
    print ('Error in ibm_ds-delete-lun: cannot import ibm_ds_common.py')
    sys.exit(1)

try:
    #OPEN THE LOG                                             
    LOG.basicConfig(level=LOG.DEBUG, filename='/dev/null')

    if not os.path.exists(os.environ['IBM_DS_LOG_DIR']):
        os.makedirs(os.environ['IBM_DS_LOG_DIR'])

    handler = LOG.handlers.RotatingFileHandler(os.environ['IBM_DS_LOG_DIR'] + '/' + os.environ['IBM_DS_LOG_FILE'], backupCount=10, maxBytes=50000000)

    if os.environ['IBM_DS_LOG_LEVEL'].lower() == 'debug':
        handler.setLevel(logging.DEBUG)
    elif os.environ['IBM_DS_LOG_LEVEL'].lower() == 'error':
        handler.setLevel(logging.ERROR)
    elif os.environ['IBM_DS_LOG_LEVEL'].lower() == 'info':
        handler.setLevel(logging.INFO)
    else:
        handler.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s -- ibm_ds-delete-lun %(process)d %(levelname)s : %(message)s')
    handler.setFormatter(formatter)

    LOG.getLogger('').addHandler(handler)

    LOG.info('Starting Logger')

except Exception as e:
    print ('Error in ibm_ds-delete-lun: Cannot open log file')
    print (type(e))
    print (e.args)
    print (e)
    sys.exit(1)

#log the environment                                                                                                                                                                                   
for i in os.environ:
    LOG.debug(str(i) + ": " + str(os.environ[i]) )

try:
    LOG.debug("ibm_ds-delete-lun: lockfile = " + str(os.environ['IBM_DS_LOCKFILE']))
    lock = FileLock(os.environ['IBM_DS_LOCKFILE'])
except Exception as e:
    LOG.error("ibm_ds-delete-lun: Could not create FileLock. " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    sys.exit(1)

try:
    with lock:
        #DO THE WORK                 
        LOG.debug("ibm_ds-delete-lun: " + str(sys.argv))

   
        IBM_DS.delete_lun(os.environ['IBM_DS_IP'],
                          os.environ['IBM_DS_PASSWORD'],
                          os.environ['UNIT_LUN_GUID'],
                          )

    print ('OK')

except Exception as e:
    LOG.error("ibm_ds-delete-lun: " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    sys.exit(1)

sys.exit(0)
