#!/usr/bin/env python
import os
import sys
import logging as LOG
import logging.handlers
import traceback

sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")

from neuca_quantum_common import *
from nova_essex_common import *

try:
    sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")
    from neuca_quantum_common import *
    from nova_essex_common import *
except:
    print ('Error in neuca-quantum-create-net: cannot import neuca_quantum_common.py')
    sys.exit(1)

try:
    #OPEN THE LOG                                                                                                                                                                                      
    LOG.basicConfig(level=LOG.DEBUG, filename='/dev/null')

    if not os.path.exists(os.environ['PROVIDER_LOG_DIR']):
        os.makedirs(os.environ['PROVIDER_LOG_DIR'])

    handler = LOG.handlers.RotatingFileHandler(os.environ['PROVIDER_LOG_DIR'] + '/' + os.environ['PROVIDER_LOG_FILE'], backupCount=10, maxBytes=50000000)

    if os.environ['PROVIDER_LOG_LEVEL'].lower() == 'debug':
        handler.setLevel(logging.DEBUG)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'error':
        handler.setLevel(logging.ERROR)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'info':
        handler.setLevel(logging.INFO)
    else:
        handler.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s -- neuca-quantum-create-net %(process)d %(levelname)s : %(message)s')
    handler.setFormatter(formatter)

    LOG.getLogger('').addHandler(handler)

    LOG.info('Starting Logger')

except Exception as e:
    print ('Error in neuca-quantum-create-net: Cannot open log file')
    print (type(e))
    print (e.args)
    print (e)
    sys.exit(1)

#log the environment                                                                                                                                                                                   
for i in os.environ:
    LOG.debug(str(i) + ": " + str(os.environ[i]) )

try:
    #DO THE WORK                                                                                                                                                                                       
    try:
        max_rate   = str(int(os.environ['QUANTUM_MAX_RATE'])/1000)
        burst_rate = str(int(os.environ['QUANTUM_BURST_RATE'])/1000)
    except:
        max_rate = None
        burst_rate = None

    network_uuid = NEuca_Quantum_Network().create_network(os.environ['QUANTUM_NET_TYPE'],
                                                        os.environ['QUANTUM_NET_NETWORK'],
                                                        os.environ['QUANTUM_NET_VLAN'],
                                                        os.environ['QUANTUM_DATAPLANE_NETWORK'],
                                                        os.environ['QUANTUM_OPENFLOW_NETWORK'],
                                                        os.environ['PROJECT_NAME'],
                                                        max_rate,
                                                        burst_rate)    
    print (network_uuid)
    
except Exception as e:
    LOG.error("neuca-quantum-create-net: " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    Project().cleanup(os.environ['PROJECT_NAME'], os.environ['USER_NAME'])
    sys.exit(1)

sys.exit(0)

