#!/usr/bin/env python
import os
import sys
import logging as LOG
import logging.handlers
import traceback

sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")

from nova_essex_common import *

try:
    sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")
    from nova_essex_common import *
except:
    print ('Error in nova-project-create: cannot import nova_essex_common.py')
    sys.exit(1)

try:
    #OPEN THE LOG                                                                                                                                                                                      
    LOG.basicConfig(level=LOG.DEBUG, filename='/dev/null')

    if not os.path.exists(os.environ['PROVIDER_LOG_DIR']):
        os.makedirs(os.environ['PROVIDER_LOG_DIR'])

    handler = LOG.handlers.RotatingFileHandler(os.environ['PROVIDER_LOG_DIR'] + '/' + os.environ['PROVIDER_LOG_FILE'], backupCount=10, maxBytes=50000000)

    if os.environ['PROVIDER_LOG_LEVEL'].lower() == 'debug':
        handler.setLevel(logging.DEBUG)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'error':
        handler.setLevel(logging.ERROR)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'info':
        handler.setLevel(logging.INFO)
    else:
        handler.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s -- nova-project-create %(process)d %(levelname)s : %(message)s')
    handler.setFormatter(formatter)

    LOG.getLogger('').addHandler(handler)

    LOG.info('Starting Logger')

except Exception as e:
    print ('Error in nova-project-create: Cannot open log file')
    print (type(e))
    print (e.args)
    print (e)
    sys.exit(1)

#log the environment                                                                                                                                                                                   
for i in os.environ:
    LOG.debug(str(i) + ": " + str(os.environ[i]) )

try:
    #DO THE WORK

    Project().setup_project(os.environ['PROJECT_NAME'], 
                  os.environ['USER_NAME'],
                  os.environ['EC2_SLICE_USER_EMAIL'], 
                  os.environ['EC2_SLICE_USER_PWD'], 
                  os.environ['EC2_SLICE_USER_ROLE'], 
                  os.environ['EC2_SLICE_ADMIN_USER'])
    print("OK")

except Exception as e:
    LOG.error("nova-project-create: " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    Project().cleanup(os.environ['PROJECT_NAME'], os.environ['USER_NAME'])
    sys.exit(1)

sys.exit(0)

