#!/usr/bin/env python                                                                                                                                                                                  
import os
import sys
import logging as LOG
import logging.handlers
import traceback

sys.path.append(os.environ['EC2_DIR'] + "/scripts")

from nova_essex_common import *

try:
    sys.path.append(os.environ['EC2_DIR'] + "/scripts")
    from nova_essex_common import *
except:
    print 'Error in nova-essex-get-userdata: cannot import nova_essex_common.py'
    sys.exit(1)

try:
    #OPEN THE LOG                                                                                                                                                                                      
    LOG.basicConfig(level=LOG.DEBUG, filename='/dev/null')

    if not os.path.exists(os.environ['EC2_LOG_DIR']):
        os.makedirs(os.environ['EC2_LOG_DIR'])

    handler = LOG.handlers.RotatingFileHandler(os.environ['EC2_LOG_DIR'] + '/' + os.environ['EC2_LOG_FILE'], backupCount=10, maxBytes=50000000)

    if os.environ['EC2_LOG_LEVEL'].lower() == 'debug':
        handler.setLevel(logging.DEBUG)
    elif os.environ['EC2_LOG_LEVEL'].lower() == 'error':
        handler.setLevel(logging.ERROR)
    elif os.environ['EC2_LOG_LEVEL'].lower() == 'info':
        handler.setLevel(logging.INFO)
    else:
        handler.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s - %(process)d - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)

    LOG.getLogger('').addHandler(handler)

    LOG.info('Starting Logger')

except Exception as e:
    print 'Error in nova-essex-get-userdata: Cannot open log file'
    print type(e)
    print e.args
    print e
    sys.exit(1)

#log the environment                                                                                                                                                                                   
#for i in os.environ:
#    LOG.debug(str(i) + ": " + str(os.environ[i]) )

try:
    #DO THE WORK                                                                                                                                                                                       
    LOG.debug("nova-essex-get-userdata: " + str(sys.argv))

    if len(sys.argv) == 2:

        instance_id = sys.argv[1].strip("'")
       
        userdata = VM.get_userdata(instance_id)

        LOG.info("nova-essex-get-userdata: Success instance_id: " + str(instance_id) )
        LOG.info("nova-essex-get-userdata: Success userdata: " + str(userdata) )
    else:
        LOG.error("nova-essex-get-userdate: invalid argv length (" + str(len(sys.argv)) + "), argv = " + str(sys.argv))
        sys.exit(1)

    print userdata

except Exception as e:
    LOG.error("nova-essex-get-userdata: " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    sys.exit(1)



sys.exit(0)


