//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.17 at 09:44:04 PM EDT 
//


package orca.util.db.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="configuration" type="{http://issg.cs.duke.edu/cod/plugins/beans}configuration" minOccurs="0"/&gt;
 *         &lt;element name="ldap" type="{http://issg.cs.duke.edu/cod/plugins/beans}ldap" minOccurs="0"/&gt;
 *         &lt;element name="mysql" type="{http://issg.cs.duke.edu/cod/plugins/beans}mysql" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configuration",
    "ldap",
    "mysql"
})
@XmlRootElement(name = "mapping")
public class Mapping {

    protected Configuration configuration;
    protected Ldap ldap;
    protected Mysql mysql;

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the ldap property.
     * 
     * @return
     *     possible object is
     *     {@link Ldap }
     *     
     */
    public Ldap getLdap() {
        return ldap;
    }

    /**
     * Sets the value of the ldap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ldap }
     *     
     */
    public void setLdap(Ldap value) {
        this.ldap = value;
    }

    /**
     * Gets the value of the mysql property.
     * 
     * @return
     *     possible object is
     *     {@link Mysql }
     *     
     */
    public Mysql getMysql() {
        return mysql;
    }

    /**
     * Sets the value of the mysql property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mysql }
     *     
     */
    public void setMysql(Mysql value) {
        this.mysql = value;
    }

}
