//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.17 at 09:44:04 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://issg.cs.duke.edu/cod/plugins/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.exogeni.orca.util.db.beans;
