//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:22 PM EDT 
//


package orca.manage.proxies.soap.beans.authority;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.manage.proxies.soap.beans.authority package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.manage.proxies.soap.beans.authority
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetReservationUnitsResponse }
     * 
     */
    public GetReservationUnitsResponse createGetReservationUnitsResponse() {
        return new GetReservationUnitsResponse();
    }

    /**
     * Create an instance of {@link GetInventoryRequest }
     * 
     */
    public GetInventoryRequest createGetInventoryRequest() {
        return new GetInventoryRequest();
    }

    /**
     * Create an instance of {@link UntransferInventoryRequest }
     * 
     */
    public UntransferInventoryRequest createUntransferInventoryRequest() {
        return new UntransferInventoryRequest();
    }

    /**
     * Create an instance of {@link TransferInventoryRequest }
     * 
     */
    public TransferInventoryRequest createTransferInventoryRequest() {
        return new TransferInventoryRequest();
    }

    /**
     * Create an instance of {@link GetAuthorityReservationsRequest }
     * 
     */
    public GetAuthorityReservationsRequest createGetAuthorityReservationsRequest() {
        return new GetAuthorityReservationsRequest();
    }

    /**
     * Create an instance of {@link UntransferInventoryResponse }
     * 
     */
    public UntransferInventoryResponse createUntransferInventoryResponse() {
        return new UntransferInventoryResponse();
    }

    /**
     * Create an instance of {@link TransferInventoryResponse }
     * 
     */
    public TransferInventoryResponse createTransferInventoryResponse() {
        return new TransferInventoryResponse();
    }

    /**
     * Create an instance of {@link GetReservationUnitsRequest }
     * 
     */
    public GetReservationUnitsRequest createGetReservationUnitsRequest() {
        return new GetReservationUnitsRequest();
    }

    /**
     * Create an instance of {@link GetUnitRequest }
     * 
     */
    public GetUnitRequest createGetUnitRequest() {
        return new GetUnitRequest();
    }

    /**
     * Create an instance of {@link GetAuthorityReservationsResponse }
     * 
     */
    public GetAuthorityReservationsResponse createGetAuthorityReservationsResponse() {
        return new GetAuthorityReservationsResponse();
    }

    /**
     * Create an instance of {@link GetUnitResponse }
     * 
     */
    public GetUnitResponse createGetUnitResponse() {
        return new GetUnitResponse();
    }

    /**
     * Create an instance of {@link GetInventoryResponse }
     * 
     */
    public GetInventoryResponse createGetInventoryResponse() {
        return new GetInventoryResponse();
    }

}
