//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.17 at 10:10:57 PM EDT 
//


package net.exogeni.orca.drivers.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.drivers.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.drivers.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Drivers }
     * @return Drivers
     */
    public Drivers createDrivers() {
        return new Drivers();
    }

    /**
     * Create an instance of {@link Driver }
     * @return Driver
     */
    public Driver createDriver() {
        return new Driver();
    }

}
