//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:09:56 PM EDT 
//


package orca.manage.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for leaseReservationMng complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaseReservationMng">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nicl.duke.edu/orca/manage/beans}ticketReservationMng">
 *       &lt;sequence>
 *         &lt;element name="authority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="joinState" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="leasedUnits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="redeemPredecessors" type="{http://www.nicl.duke.edu/orca/manage/beans}reservationPredecessorMng" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaseReservationMng", propOrder = {
    "authority",
    "joinState",
    "leasedUnits",
    "redeemPredecessors"
})
public class LeaseReservationMng
    extends TicketReservationMng
{

    @XmlElement(required = true)
    protected String authority;
    protected int joinState;
    protected int leasedUnits;
    protected List<ReservationPredecessorMng> redeemPredecessors;

    /**
     * Gets the value of the authority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets the value of the authority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthority(String value) {
        this.authority = value;
    }

    /**
     * Gets the value of the joinState property.
     * 
     */
    public int getJoinState() {
        return joinState;
    }

    /**
     * Sets the value of the joinState property.
     * 
     */
    public void setJoinState(int value) {
        this.joinState = value;
    }

    /**
     * Gets the value of the leasedUnits property.
     * 
     */
    public int getLeasedUnits() {
        return leasedUnits;
    }

    /**
     * Sets the value of the leasedUnits property.
     * 
     */
    public void setLeasedUnits(int value) {
        this.leasedUnits = value;
    }

    /**
     * Gets the value of the redeemPredecessors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the redeemPredecessors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRedeemPredecessors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReservationPredecessorMng }
     * 
     * 
     */
    public List<ReservationPredecessorMng> getRedeemPredecessors() {
        if (redeemPredecessors == null) {
            redeemPredecessors = new ArrayList<ReservationPredecessorMng>();
        }
        return this.redeemPredecessors;
    }

}
