//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:09:56 PM EDT 
//


package orca.manage.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logicalMachineMng complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logicalMachineMng">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalCPU" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="totalMemory" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="totalBandwidth" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="totalStorage" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logicalMachineMng", propOrder = {
    "id",
    "totalCPU",
    "totalMemory",
    "totalBandwidth",
    "totalStorage"
})
public class LogicalMachineMng {

    @XmlElement(required = true)
    protected String id;
    protected long totalCPU;
    protected long totalMemory;
    protected long totalBandwidth;
    protected long totalStorage;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the totalCPU property.
     * 
     */
    public long getTotalCPU() {
        return totalCPU;
    }

    /**
     * Sets the value of the totalCPU property.
     * 
     */
    public void setTotalCPU(long value) {
        this.totalCPU = value;
    }

    /**
     * Gets the value of the totalMemory property.
     * 
     */
    public long getTotalMemory() {
        return totalMemory;
    }

    /**
     * Sets the value of the totalMemory property.
     * 
     */
    public void setTotalMemory(long value) {
        this.totalMemory = value;
    }

    /**
     * Gets the value of the totalBandwidth property.
     * 
     */
    public long getTotalBandwidth() {
        return totalBandwidth;
    }

    /**
     * Sets the value of the totalBandwidth property.
     * 
     */
    public void setTotalBandwidth(long value) {
        this.totalBandwidth = value;
    }

    /**
     * Gets the value of the totalStorage property.
     * 
     */
    public long getTotalStorage() {
        return totalStorage;
    }

    /**
     * Sets the value of the totalStorage property.
     * 
     */
    public void setTotalStorage(long value) {
        this.totalStorage = value;
    }

}
