//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:09:56 PM EDT 
//


package orca.manage.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.manage.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.manage.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultMng }
     * 
     */
    public ResultMng createResultMng() {
        return new ResultMng();
    }

    /**
     * Create an instance of {@link ResultEventMng }
     * 
     */
    public ResultEventMng createResultEventMng() {
        return new ResultEventMng();
    }

    /**
     * Create an instance of {@link ReservationStateMng }
     * 
     */
    public ReservationStateMng createReservationStateMng() {
        return new ReservationStateMng();
    }

    /**
     * Create an instance of {@link ResultActorMng }
     * 
     */
    public ResultActorMng createResultActorMng() {
        return new ResultActorMng();
    }

    /**
     * Create an instance of {@link ResultMachineMng }
     * 
     */
    public ResultMachineMng createResultMachineMng() {
        return new ResultMachineMng();
    }

    /**
     * Create an instance of {@link AuthorityBasePolicyControlMng }
     * 
     */
    public AuthorityBasePolicyControlMng createAuthorityBasePolicyControlMng() {
        return new AuthorityBasePolicyControlMng();
    }

    /**
     * Create an instance of {@link PropertyMng }
     * 
     */
    public PropertyMng createPropertyMng() {
        return new PropertyMng();
    }

    /**
     * Create an instance of {@link ResultUserMng }
     * 
     */
    public ResultUserMng createResultUserMng() {
        return new ResultUserMng();
    }

    /**
     * Create an instance of {@link PluginMng }
     * 
     */
    public PluginMng createPluginMng() {
        return new PluginMng();
    }

    /**
     * Create an instance of {@link ReservationMng }
     * 
     */
    public ReservationMng createReservationMng() {
        return new ReservationMng();
    }

    /**
     * Create an instance of {@link AuthTokenMng }
     * 
     */
    public AuthTokenMng createAuthTokenMng() {
        return new AuthTokenMng();
    }

    /**
     * Create an instance of {@link MachineMng }
     * 
     */
    public MachineMng createMachineMng() {
        return new MachineMng();
    }

    /**
     * Create an instance of {@link StorageServerMng }
     * 
     */
    public StorageServerMng createStorageServerMng() {
        return new StorageServerMng();
    }

    /**
     * Create an instance of {@link ControllerMng }
     * 
     */
    public ControllerMng createControllerMng() {
        return new ControllerMng();
    }

    /**
     * Create an instance of {@link PropertiesMng }
     * 
     */
    public PropertiesMng createPropertiesMng() {
        return new PropertiesMng();
    }

    /**
     * Create an instance of {@link UserMng }
     * 
     */
    public UserMng createUserMng() {
        return new UserMng();
    }

    /**
     * Create an instance of {@link ResultPackageMng }
     * 
     */
    public ResultPackageMng createResultPackageMng() {
        return new ResultPackageMng();
    }

    /**
     * Create an instance of {@link ResultCertificateMng }
     * 
     */
    public ResultCertificateMng createResultCertificateMng() {
        return new ResultCertificateMng();
    }

    /**
     * Create an instance of {@link LeaseReservationMng }
     * 
     */
    public LeaseReservationMng createLeaseReservationMng() {
        return new LeaseReservationMng();
    }

    /**
     * Create an instance of {@link ResultSliceMng }
     * 
     */
    public ResultSliceMng createResultSliceMng() {
        return new ResultSliceMng();
    }

    /**
     * Create an instance of {@link ConfigMappingMng }
     * 
     */
    public ConfigMappingMng createConfigMappingMng() {
        return new ConfigMappingMng();
    }

    /**
     * Create an instance of {@link StorageServerTypeMng }
     * 
     */
    public StorageServerTypeMng createStorageServerTypeMng() {
        return new StorageServerTypeMng();
    }

    /**
     * Create an instance of {@link ProxyMng }
     * 
     */
    public ProxyMng createProxyMng() {
        return new ProxyMng();
    }

    /**
     * Create an instance of {@link ProtocolProxyMng }
     * 
     */
    public ProtocolProxyMng createProtocolProxyMng() {
        return new ProtocolProxyMng();
    }

    /**
     * Create an instance of {@link ResultActorDescriptorMng }
     * 
     */
    public ResultActorDescriptorMng createResultActorDescriptorMng() {
        return new ResultActorDescriptorMng();
    }

    /**
     * Create an instance of {@link PoolInfoMng }
     * 
     */
    public PoolInfoMng createPoolInfoMng() {
        return new PoolInfoMng();
    }

    /**
     * Create an instance of {@link ResultStringsMng }
     * 
     */
    public ResultStringsMng createResultStringsMng() {
        return new ResultStringsMng();
    }

    /**
     * Create an instance of {@link LeaseReservationStateMng }
     * 
     */
    public LeaseReservationStateMng createLeaseReservationStateMng() {
        return new LeaseReservationStateMng();
    }

    /**
     * Create an instance of {@link ResultPoolInfoMng }
     * 
     */
    public ResultPoolInfoMng createResultPoolInfoMng() {
        return new ResultPoolInfoMng();
    }

    /**
     * Create an instance of {@link ActorDescriptorMng }
     * 
     */
    public ActorDescriptorMng createActorDescriptorMng() {
        return new ActorDescriptorMng();
    }

    /**
     * Create an instance of {@link LogicalMachineMng }
     * 
     */
    public LogicalMachineMng createLogicalMachineMng() {
        return new LogicalMachineMng();
    }

    /**
     * Create an instance of {@link ResourceCalendarMng }
     * 
     */
    public ResourceCalendarMng createResourceCalendarMng() {
        return new ResourceCalendarMng();
    }

    /**
     * Create an instance of {@link ResultIdControlInventoryMng }
     * 
     */
    public ResultIdControlInventoryMng createResultIdControlInventoryMng() {
        return new ResultIdControlInventoryMng();
    }

    /**
     * Create an instance of {@link ReservationStateTransitionEventMng }
     * 
     */
    public ReservationStateTransitionEventMng createReservationStateTransitionEventMng() {
        return new ReservationStateTransitionEventMng();
    }

    /**
     * Create an instance of {@link ResultBooleanMng }
     * 
     */
    public ResultBooleanMng createResultBooleanMng() {
        return new ResultBooleanMng();
    }

    /**
     * Create an instance of {@link LogicalMachineCalendarMng }
     * 
     */
    public LogicalMachineCalendarMng createLogicalMachineCalendarMng() {
        return new LogicalMachineCalendarMng();
    }

    /**
     * Create an instance of {@link PortalPluginDescriptorMng }
     * 
     */
    public PortalPluginDescriptorMng createPortalPluginDescriptorMng() {
        return new PortalPluginDescriptorMng();
    }

    /**
     * Create an instance of {@link ResultNodeMng }
     * 
     */
    public ResultNodeMng createResultNodeMng() {
        return new ResultNodeMng();
    }

    /**
     * Create an instance of {@link ResultProxyMng }
     * 
     */
    public ResultProxyMng createResultProxyMng() {
        return new ResultProxyMng();
    }

    /**
     * Create an instance of {@link SliceMng }
     * 
     */
    public SliceMng createSliceMng() {
        return new SliceMng();
    }

    /**
     * Create an instance of {@link ClientMng }
     * 
     */
    public ClientMng createClientMng() {
        return new ClientMng();
    }

    /**
     * Create an instance of {@link ResultStorageServerTypeMng }
     * 
     */
    public ResultStorageServerTypeMng createResultStorageServerTypeMng() {
        return new ResultStorageServerTypeMng();
    }

    /**
     * Create an instance of {@link ResultReservationStateMng }
     * 
     */
    public ResultReservationStateMng createResultReservationStateMng() {
        return new ResultReservationStateMng();
    }

    /**
     * Create an instance of {@link ProtocolProxiesMng }
     * 
     */
    public ProtocolProxiesMng createProtocolProxiesMng() {
        return new ProtocolProxiesMng();
    }

    /**
     * Create an instance of {@link UnitMng }
     * 
     */
    public UnitMng createUnitMng() {
        return new UnitMng();
    }

    /**
     * Create an instance of {@link ResultAuthorityBasePolicyControlMng }
     * 
     */
    public ResultAuthorityBasePolicyControlMng createResultAuthorityBasePolicyControlMng() {
        return new ResultAuthorityBasePolicyControlMng();
    }

    /**
     * Create an instance of {@link ResultControlerMng }
     * 
     */
    public ResultControlerMng createResultControlerMng() {
        return new ResultControlerMng();
    }

    /**
     * Create an instance of {@link XmlConfigMng }
     * 
     */
    public XmlConfigMng createXmlConfigMng() {
        return new XmlConfigMng();
    }

    /**
     * Create an instance of {@link PluginCreateMng }
     * 
     */
    public PluginCreateMng createPluginCreateMng() {
        return new PluginCreateMng();
    }

    /**
     * Create an instance of {@link ResourceCalendarEntryMng }
     * 
     */
    public ResourceCalendarEntryMng createResourceCalendarEntryMng() {
        return new ResourceCalendarEntryMng();
    }

    /**
     * Create an instance of {@link ResultReservationMng }
     * 
     */
    public ResultReservationMng createResultReservationMng() {
        return new ResultReservationMng();
    }

    /**
     * Create an instance of {@link ResultClientMng }
     * 
     */
    public ResultClientMng createResultClientMng() {
        return new ResultClientMng();
    }

    /**
     * Create an instance of {@link NodeMng }
     * 
     */
    public NodeMng createNodeMng() {
        return new NodeMng();
    }

    /**
     * Create an instance of {@link ReservationPredecessorMng }
     * 
     */
    public ReservationPredecessorMng createReservationPredecessorMng() {
        return new ReservationPredecessorMng();
    }

    /**
     * Create an instance of {@link TermMng }
     * 
     */
    public TermMng createTermMng() {
        return new TermMng();
    }

    /**
     * Create an instance of {@link IdControlInventoryMng }
     * 
     */
    public IdControlInventoryMng createIdControlInventoryMng() {
        return new IdControlInventoryMng();
    }

    /**
     * Create an instance of {@link ResultUnitMng }
     * 
     */
    public ResultUnitMng createResultUnitMng() {
        return new ResultUnitMng();
    }

    /**
     * Create an instance of {@link PluginsMng }
     * 
     */
    public PluginsMng createPluginsMng() {
        return new PluginsMng();
    }

    /**
     * Create an instance of {@link CertificateMng }
     * 
     */
    public CertificateMng createCertificateMng() {
        return new CertificateMng();
    }

    /**
     * Create an instance of {@link ActorMng }
     * 
     */
    public ActorMng createActorMng() {
        return new ActorMng();
    }

    /**
     * Create an instance of {@link ActorCreateMng }
     * 
     */
    public ActorCreateMng createActorCreateMng() {
        return new ActorCreateMng();
    }

    /**
     * Create an instance of {@link TicketReservationMng }
     * 
     */
    public TicketReservationMng createTicketReservationMng() {
        return new TicketReservationMng();
    }

    /**
     * Create an instance of {@link GenericEventMng }
     * 
     */
    public GenericEventMng createGenericEventMng() {
        return new GenericEventMng();
    }

    /**
     * Create an instance of {@link PackageMng }
     * 
     */
    public PackageMng createPackageMng() {
        return new PackageMng();
    }

    /**
     * Create an instance of {@link ResultXmlConfigMng }
     * 
     */
    public ResultXmlConfigMng createResultXmlConfigMng() {
        return new ResultXmlConfigMng();
    }

    /**
     * Create an instance of {@link ResultStorageServerMng }
     * 
     */
    public ResultStorageServerMng createResultStorageServerMng() {
        return new ResultStorageServerMng();
    }

    /**
     * Create an instance of {@link ListMng }
     * 
     */
    public ListMng createListMng() {
        return new ListMng();
    }

    /**
     * Create an instance of {@link IdControlInventoryItemMng }
     * 
     */
    public IdControlInventoryItemMng createIdControlInventoryItemMng() {
        return new IdControlInventoryItemMng();
    }

    /**
     * Create an instance of {@link ResultBytesMng }
     * 
     */
    public ResultBytesMng createResultBytesMng() {
        return new ResultBytesMng();
    }

    /**
     * Create an instance of {@link ResultPluginMng }
     * 
     */
    public ResultPluginMng createResultPluginMng() {
        return new ResultPluginMng();
    }

    /**
     * Create an instance of {@link ResultStringMng }
     * 
     */
    public ResultStringMng createResultStringMng() {
        return new ResultStringMng();
    }

}
