//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.29 at 01:30:39 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nicl.duke.edu/orca/manage/beans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package orca.manage.beans;
