//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:19 PM EDT 
//


package net.exogeni.orca.manage.proxies.soap.beans.actor;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.exogeni.orca.manage.proxies.soap.beans.actor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.exogeni.orca.manage.proxies.soap.beans.actor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateReservationRequest }
     * 
     * @return created instance 
     */
    public UpdateReservationRequest createUpdateReservationRequest() {
        return new UpdateReservationRequest();
    }

    /**
     * Create an instance of {@link GetSlicesResponse }
     * 
     * @return created instance 
     */
    public GetSlicesResponse createGetSlicesResponse() {
        return new GetSlicesResponse();
    }

    /**
     * Create an instance of {@link GetReservationsResponse }
     * 
     * @return created instance 
     */
    public GetReservationsResponse createGetReservationsResponse() {
        return new GetReservationsResponse();
    }

    /**
     * Create an instance of {@link GetActorNameResponse }
     * 
     * @return created instance 
     */
    public GetActorNameResponse createGetActorNameResponse() {
        return new GetActorNameResponse();
    }

    /**
     * Create an instance of {@link RegisterCertificateRequest }
     * 
     * @return created instance 
     */
    public RegisterCertificateRequest createRegisterCertificateRequest() {
        return new RegisterCertificateRequest();
    }

    /**
     * Create an instance of {@link UnregisterCertificateResponse }
     * 
     * @return created instance 
     */
    public UnregisterCertificateResponse createUnregisterCertificateResponse() {
        return new UnregisterCertificateResponse();
    }

    /**
     * Create an instance of {@link AddSliceRequest }
     * 
     * @return created instance 
     */
    public AddSliceRequest createAddSliceRequest() {
        return new AddSliceRequest();
    }

    /**
     * Create an instance of {@link RemoveReservationResponse }
     * 
     * @return created instance 
     */
    public RemoveReservationResponse createRemoveReservationResponse() {
        return new RemoveReservationResponse();
    }

    /**
     * Create an instance of {@link GetReservationsStateResponse }
     * 
     * @return created instance 
     */
    public GetReservationsStateResponse createGetReservationsStateResponse() {
        return new GetReservationsStateResponse();
    }

    /**
     * Create an instance of {@link GetReservationStateResponse }
     * 
     * @return created instance 
     */
    public GetReservationStateResponse createGetReservationStateResponse() {
        return new GetReservationStateResponse();
    }

    /**
     * Create an instance of {@link CloseSliceReservationsResponse }
     * 
     * @return created instance 
     */
    public CloseSliceReservationsResponse createCloseSliceReservationsResponse() {
        return new CloseSliceReservationsResponse();
    }

    /**
     * Create an instance of {@link DrainEventsRequest }
     * 
     * @return created instance 
     */
    public DrainEventsRequest createDrainEventsRequest() {
        return new DrainEventsRequest();
    }

    /**
     * Create an instance of {@link DeleteEventSubscriptionResponse }
     * 
     * @return created instance 
     */
    public DeleteEventSubscriptionResponse createDeleteEventSubscriptionResponse() {
        return new DeleteEventSubscriptionResponse();
    }

    /**
     * Create an instance of {@link GetActorNameRequest }
     * 
     * @return created instance 
     */
    public GetActorNameRequest createGetActorNameRequest() {
        return new GetActorNameRequest();
    }

    /**
     * Create an instance of {@link RegisterCertificateResponse }
     * 
     * @return created instance 
     */
    public RegisterCertificateResponse createRegisterCertificateResponse() {
        return new RegisterCertificateResponse();
    }

    /**
     * Create an instance of {@link GetCertificateRequest }
     * 
     * @return created instance 
     */
    public GetCertificateRequest createGetCertificateRequest() {
        return new GetCertificateRequest();
    }

    /**
     * Create an instance of {@link AddSliceResponse }
     * 
     * @return created instance 
     */
    public AddSliceResponse createAddSliceResponse() {
        return new AddSliceResponse();
    }

    /**
     * Create an instance of {@link GetReservationResponse }
     * 
     * @return created instance 
     */
    public GetReservationResponse createGetReservationResponse() {
        return new GetReservationResponse();
    }

    /**
     * Create an instance of {@link GetReservationRequest }
     * 
     * @return created instance 
     */
    public GetReservationRequest createGetReservationRequest() {
        return new GetReservationRequest();
    }

    /**
     * Create an instance of {@link CreateEventSubscriptionResponse }
     * 
     * @return created instance 
     */
    public CreateEventSubscriptionResponse createCreateEventSubscriptionResponse() {
        return new CreateEventSubscriptionResponse();
    }

    /**
     * Create an instance of {@link GetReservationsStateRequest }
     * 
     * @return created instance 
     */
    public GetReservationsStateRequest createGetReservationsStateRequest() {
        return new GetReservationsStateRequest();
    }

    /**
     * Create an instance of {@link UpdateReservationResponse }
     * 
     * @return created instance 
     */
    public UpdateReservationResponse createUpdateReservationResponse() {
        return new UpdateReservationResponse();
    }

    /**
     * Create an instance of {@link UnregisterCertificateRequest }
     * 
     * @return created instance 
     */
    public UnregisterCertificateRequest createUnregisterCertificateRequest() {
        return new UnregisterCertificateRequest();
    }

    /**
     * Create an instance of {@link CreateEventSubscriptionRequest }
     * 
     * @return created instance 
     */
    public CreateEventSubscriptionRequest createCreateEventSubscriptionRequest() {
        return new CreateEventSubscriptionRequest();
    }

    /**
     * Create an instance of {@link GetSliceResponse }
     * 
     * @return created instance 
     */
    public GetSliceResponse createGetSliceResponse() {
        return new GetSliceResponse();
    }

    /**
     * Create an instance of {@link GetSlicesRequest }
     * 
     * @return created instance 
     */
    public GetSlicesRequest createGetSlicesRequest() {
        return new GetSlicesRequest();
    }

    /**
     * Create an instance of {@link UpdateSliceResponse }
     * 
     * @return created instance 
     */
    public UpdateSliceResponse createUpdateSliceResponse() {
        return new UpdateSliceResponse();
    }

    /**
     * Create an instance of {@link CloseReservationResponse }
     * 
     * @return created instance 
     */
    public CloseReservationResponse createCloseReservationResponse() {
        return new CloseReservationResponse();
    }

    /**
     * Create an instance of {@link DeleteEventSubscriptionRequest }
     * 
     * @return created instance 
     */
    public DeleteEventSubscriptionRequest createDeleteEventSubscriptionRequest() {
        return new DeleteEventSubscriptionRequest();
    }

    /**
     * Create an instance of {@link GetReservationStateRequest }
     * 
     * @return created instance 
     */
    public GetReservationStateRequest createGetReservationStateRequest() {
        return new GetReservationStateRequest();
    }

    /**
     * Create an instance of {@link DrainEventsResponse }
     * 
     * @return created instance 
     */
    public DrainEventsResponse createDrainEventsResponse() {
        return new DrainEventsResponse();
    }

    /**
     * Create an instance of {@link RemoveSliceRequest }
     * 
     * @return created instance 
     */
    public RemoveSliceRequest createRemoveSliceRequest() {
        return new RemoveSliceRequest();
    }

    /**
     * Create an instance of {@link GetSliceRequest }
     * 
     * @return created instance 
     */
    public GetSliceRequest createGetSliceRequest() {
        return new GetSliceRequest();
    }

    /**
     * Create an instance of {@link CloseReservationRequest }
     * 
     * @return created instance 
     */
    public CloseReservationRequest createCloseReservationRequest() {
        return new CloseReservationRequest();
    }

    /**
     * Create an instance of {@link UpdateSliceRequest }
     * 
     * @return created instance 
     */
    public UpdateSliceRequest createUpdateSliceRequest() {
        return new UpdateSliceRequest();
    }

    /**
     * Create an instance of {@link RemoveReservationRequest }
     * 
     * @return created instance 
     */
    public RemoveReservationRequest createRemoveReservationRequest() {
        return new RemoveReservationRequest();
    }

    /**
     * Create an instance of {@link RemoveSliceResponse }
     * 
     * @return created instance 
     */
    public RemoveSliceResponse createRemoveSliceResponse() {
        return new RemoveSliceResponse();
    }

    /**
     * Create an instance of {@link CloseSliceReservationsRequest }
     * 
     * @return created instance 
     */
    public CloseSliceReservationsRequest createCloseSliceReservationsRequest() {
        return new CloseSliceReservationsRequest();
    }

    /**
     * Create an instance of {@link GetCertificateResponse }
     * 
     * @return created instance 
     */
    public GetCertificateResponse createGetCertificateResponse() {
        return new GetCertificateResponse();
    }

    /**
     * Create an instance of {@link GetReservationsRequest }
     * 
     * @return created instance 
     */
    public GetReservationsRequest createGetReservationsRequest() {
        return new GetReservationsRequest();
    }

}
