//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.08 at 05:33:55 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://issg.cs.duke.edu/sharp/boot", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.exogeni.orca.boot.beans;
