//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.08 at 05:33:55 PM AST 
//


package net.exogeni.orca.boot.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rdata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rdata"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="localProperties" type="{http://issg.cs.duke.edu/sharp/boot}simpleParameters" minOccurs="0"/&gt;
 *         &lt;element name="requestProperties" type="{http://issg.cs.duke.edu/sharp/boot}simpleParameters" minOccurs="0"/&gt;
 *         &lt;element name="resourceProperties" type="{http://issg.cs.duke.edu/sharp/boot}simpleParameters" minOccurs="0"/&gt;
 *         &lt;element name="configurationProperties" type="{http://issg.cs.duke.edu/sharp/boot}simpleParameters" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rdata", propOrder = {

})
public class Rdata {

    protected SimpleParameters localProperties;
    protected SimpleParameters requestProperties;
    protected SimpleParameters resourceProperties;
    protected SimpleParameters configurationProperties;

    /**
     * Gets the value of the localProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleParameters }
     *     
     */
    public SimpleParameters getLocalProperties() {
        return localProperties;
    }

    /**
     * Sets the value of the localProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleParameters }
     *     
     */
    public void setLocalProperties(SimpleParameters value) {
        this.localProperties = value;
    }

    /**
     * Gets the value of the requestProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleParameters }
     *     
     */
    public SimpleParameters getRequestProperties() {
        return requestProperties;
    }

    /**
     * Sets the value of the requestProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleParameters }
     *     
     */
    public void setRequestProperties(SimpleParameters value) {
        this.requestProperties = value;
    }

    /**
     * Gets the value of the resourceProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleParameters }
     *     
     */
    public SimpleParameters getResourceProperties() {
        return resourceProperties;
    }

    /**
     * Sets the value of the resourceProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleParameters }
     *     
     */
    public void setResourceProperties(SimpleParameters value) {
        this.resourceProperties = value;
    }

    /**
     * Gets the value of the configurationProperties property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleParameters }
     *     
     */
    public SimpleParameters getConfigurationProperties() {
        return configurationProperties;
    }

    /**
     * Sets the value of the configurationProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleParameters }
     *     
     */
    public void setConfigurationProperties(SimpleParameters value) {
        this.configurationProperties = value;
    }

}
