//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:09:56 PM EDT 
//


package net.exogeni.orca.manage.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logicalMachineCalendarMng complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logicalMachineCalendarMng"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="cpu" type="{http://www.nicl.duke.edu/orca/manage/beans}resourceCalendarMng"/&gt;
 *         &lt;element name="memory" type="{http://www.nicl.duke.edu/orca/manage/beans}resourceCalendarMng"/&gt;
 *         &lt;element name="bandwidth" type="{http://www.nicl.duke.edu/orca/manage/beans}resourceCalendarMng"/&gt;
 *         &lt;element name="disk" type="{http://www.nicl.duke.edu/orca/manage/beans}resourceCalendarMng"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logicalMachineCalendarMng", propOrder = {
    "cpu",
    "memory",
    "bandwidth",
    "disk"
})
public class LogicalMachineCalendarMng {

    @XmlElement(required = true)
    protected ResourceCalendarMng cpu;
    @XmlElement(required = true)
    protected ResourceCalendarMng memory;
    @XmlElement(required = true)
    protected ResourceCalendarMng bandwidth;
    @XmlElement(required = true)
    protected ResourceCalendarMng disk;

    /**
     * Gets the value of the cpu property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public ResourceCalendarMng getCpu() {
        return cpu;
    }

    /**
     * Sets the value of the cpu property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public void setCpu(ResourceCalendarMng value) {
        this.cpu = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public ResourceCalendarMng getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public void setMemory(ResourceCalendarMng value) {
        this.memory = value;
    }

    /**
     * Gets the value of the bandwidth property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public ResourceCalendarMng getBandwidth() {
        return bandwidth;
    }

    /**
     * Sets the value of the bandwidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public void setBandwidth(ResourceCalendarMng value) {
        this.bandwidth = value;
    }

    /**
     * Gets the value of the disk property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public ResourceCalendarMng getDisk() {
        return disk;
    }

    /**
     * Sets the value of the disk property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCalendarMng }
     *     
     */
    public void setDisk(ResourceCalendarMng value) {
        this.disk = value;
    }

}
