#!/bin/bash

if [ -r /opt/orca/nodeagent/data/drivers.xml ]; then
	echo "drivers.xml already exists"
else
	cp /opt/orca/nodeagent/temp/drivers.xml /opt/orca/nodeagent/data/drivers.xml
fi

rm -rf /opt/orca/nodeagent/temp

update-rc.d orca-nodeagent defaults 15 10 > /dev/null
chmod u+x /etc/init.d/orca-nodeagent
/etc/init.d/orca-nodeagent start

