#!/usr/bin/env python                                                                                                                                                                                  
import os
import sys
import logging as LOG
import logging.handlers
import traceback

sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")

from neuca_quantum_common import *

try:
    sys.path.append(os.environ['PROVIDER_DIR'] + "/scripts")
    from neuca_quantum_common import *
except:
    print 'Error in neuca-quantum-delete-net: cannot import neuca_quantum_common.py'
    sys.exit(1)

try:
    #OPEN THE LOG                                                                                                                                                                                      
    LOG.basicConfig(level=LOG.DEBUG, filename='/dev/null')

    if not os.path.exists(os.environ['PROVIDER_LOG_DIR']):
        os.makedirs(os.environ['PROVIDER_LOG_DIR'])

    handler = LOG.handlers.RotatingFileHandler(os.environ['PROVIDER_LOG_DIR'] + '/' + os.environ['PROVIDER_LOG_FILE'], backupCount=10, maxBytes=50000000)

    if os.environ['PROVIDER_LOG_LEVEL'].lower() == 'debug':
        handler.setLevel(logging.DEBUG)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'error':
        handler.setLevel(logging.ERROR)
    elif os.environ['PROVIDER_LOG_LEVEL'].lower() == 'info':
        handler.setLevel(logging.INFO)
    else:
        handler.setLevel(logging.INFO)

    formatter = logging.Formatter('%(asctime)s -- neuca-quantum-delete-net %(process)d %(levelname)s : %(message)s')
    handler.setFormatter(formatter)

    LOG.getLogger('').addHandler(handler)

    LOG.info('Starting Logger')

except Exception as e:
    print 'Error in neuca-quantum-delete-net: Cannot open log file'
    print type(e)
    print e.args
    print e
    sys.exit(1)

#log the environment                                                                                                                                                                                   
for i in os.environ:
    LOG.debug(str(i) + ": " + str(os.environ[i]) )

try:
    #DO THE WORK                                                                                                                                                                                       
    LOG.debug("neuca-quantum-delete-net: " + str(sys.argv))
    try:
        max_rate   = os.environ['QUANTUM_MAX_RATE']
        burst_rate = os.environ['QUANTUM_BURST_RATE']
    except:
        max_rate = None
        burst_rate = None

    NEuca_Quantum_Network.delete_network(os.environ['QUANTUM_TENANT_ID'],
                                         os.environ['QUANTUM_NET_UUID'])
 
    print 'OK'

except Exception as e:
    LOG.error("neuca-quantum-delete-net: " + str(type(e)) + " : " + str(e) + "\n" + str(traceback.format_exc()))
    sys.exit(1)

sys.exit(0)
