//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:20 PM EDT 
//


package orca.manage.proxies.soap.beans.serveractor;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.manage.proxies.soap.beans.serveractor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.manage.proxies.soap.beans.serveractor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetClientCertificateRequest }
     * @return created instance
     */
    public GetClientCertificateRequest createGetClientCertificateRequest() {
        return new GetClientCertificateRequest();
    }

    /**
     * Create an instance of {@link GetClientReservationsResponse }
     * 
     * @return created instance
     */
    public GetClientReservationsResponse createGetClientReservationsResponse() {
        return new GetClientReservationsResponse();
    }

    /**
     * Create an instance of {@link GetClientSlicesRequest }
     * 
     * @return created instance
     */
    public GetClientSlicesRequest createGetClientSlicesRequest() {
        return new GetClientSlicesRequest();
    }

    /**
     * Create an instance of {@link UnregisterClientRequest }
     * 
     * @return created instance
     */
    public UnregisterClientRequest createUnregisterClientRequest() {
        return new UnregisterClientRequest();
    }

    /**
     * Create an instance of {@link ExportResourcesRequest }
     * 
     * @return created instance
     */
    public ExportResourcesRequest createExportResourcesRequest() {
        return new ExportResourcesRequest();
    }

    /**
     * Create an instance of {@link GetInventorySlicesResponse }
     * 
     * @return created instance
     */
    public GetInventorySlicesResponse createGetInventorySlicesResponse() {
        return new GetInventorySlicesResponse();
    }

    /**
     * Create an instance of {@link AddClientSliceResponse }
     * 
     * @return created instance
     */
    public AddClientSliceResponse createAddClientSliceResponse() {
        return new AddClientSliceResponse();
    }

    /**
     * Create an instance of {@link GetBrokerReservationsResponse }
     * 
     * @return created instance
     */
    public GetBrokerReservationsResponse createGetBrokerReservationsResponse() {
        return new GetBrokerReservationsResponse();
    }

    /**
     * Create an instance of {@link GetInventoryReservationsRequest }
     * 
     * @return created instance
     */
    public GetInventoryReservationsRequest createGetInventoryReservationsRequest() {
        return new GetInventoryReservationsRequest();
    }

    /**
     * Create an instance of {@link GetClientsRequest }
     * 
     * @return created instance
     */
    public GetClientsRequest createGetClientsRequest() {
        return new GetClientsRequest();
    }

    /**
     * Create an instance of {@link GetClientReservationsRequest }
     * 
     * @return created instance
     */
    public GetClientReservationsRequest createGetClientReservationsRequest() {
        return new GetClientReservationsRequest();
    }

    /**
     * Create an instance of {@link GetClientSlicesResponse }
     * 
     * @return created instance
     */
    public GetClientSlicesResponse createGetClientSlicesResponse() {
        return new GetClientSlicesResponse();
    }

    /**
     * Create an instance of {@link ExportResourcesResponse }
     * 
     * @return created instance
     */
    public ExportResourcesResponse createExportResourcesResponse() {
        return new ExportResourcesResponse();
    }

    /**
     * Create an instance of {@link GetInventoryReservationsResponse }
     * 
     * @return created instance
     */
    public GetInventoryReservationsResponse createGetInventoryReservationsResponse() {
        return new GetInventoryReservationsResponse();
    }

    /**
     * Create an instance of {@link GetClientsResponse }
     * 
     * @return created instance
     */
    public GetClientsResponse createGetClientsResponse() {
        return new GetClientsResponse();
    }

    /**
     * Create an instance of {@link GetClientResponse }
     * 
     * @return created instance
     */
    public GetClientResponse createGetClientResponse() {
        return new GetClientResponse();
    }

    /**
     * Create an instance of {@link AddClientSliceRequest }
     * 
     * @return created instance
     */
    public AddClientSliceRequest createAddClientSliceRequest() {
        return new AddClientSliceRequest();
    }

    /**
     * Create an instance of {@link GetClientCertificateResponse }
     * 
     * @return created instance
     */
    public GetClientCertificateResponse createGetClientCertificateResponse() {
        return new GetClientCertificateResponse();
    }

    /**
     * Create an instance of {@link GetBrokerReservationsRequest }
     * 
     * @return created instance
     */
    public GetBrokerReservationsRequest createGetBrokerReservationsRequest() {
        return new GetBrokerReservationsRequest();
    }

    /**
     * Create an instance of {@link UnregisterClientResponse }
     * 
     * @return created instance
     */
    public UnregisterClientResponse createUnregisterClientResponse() {
        return new UnregisterClientResponse();
    }

    /**
     * Create an instance of {@link GetInventorySlicesRequest }
     * 
     * @return created instance
     */
    public GetInventorySlicesRequest createGetInventorySlicesRequest() {
        return new GetInventorySlicesRequest();
    }

    /**
     * Create an instance of {@link RegisterClientResponse }
     * 
     * @return created instance
     */
    public RegisterClientResponse createRegisterClientResponse() {
        return new RegisterClientResponse();
    }

    /**
     * Create an instance of {@link RegisterClientRequest }
     * 
     * @return created instance
     */
    public RegisterClientRequest createRegisterClientRequest() {
        return new RegisterClientRequest();
    }

    /**
     * Create an instance of {@link GetClientRequest }
     * 
     * @return created instance
     */
    public GetClientRequest createGetClientRequest() {
        return new GetClientRequest();
    }

}
