//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.06 at 05:12:18 PM EDT 
//


package orca.manage.proxies.soap.beans.container;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orca.manage.proxies.soap.beans.container package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orca.manage.proxies.soap.beans.container
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetInventoryRequest }
     * 
     */
    public GetInventoryRequest createGetInventoryRequest() {
        return new GetInventoryRequest();
    }

    /**
     * Create an instance of {@link SetUserPasswordRequest }
     * 
     */
    public SetUserPasswordRequest createSetUserPasswordRequest() {
        return new SetUserPasswordRequest();
    }

    /**
     * Create an instance of {@link GetPackagesRequest }
     * 
     */
    public GetPackagesRequest createGetPackagesRequest() {
        return new GetPackagesRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     * 
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link GetPluginRequest }
     * 
     */
    public GetPluginRequest createGetPluginRequest() {
        return new GetPluginRequest();
    }

    /**
     * Create an instance of {@link GetPackagesResponse }
     * 
     */
    public GetPackagesResponse createGetPackagesResponse() {
        return new GetPackagesResponse();
    }

    /**
     * Create an instance of {@link GetUnitResponse }
     * 
     */
    public GetUnitResponse createGetUnitResponse() {
        return new GetUnitResponse();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link GetCertificateRequest }
     * 
     */
    public GetCertificateRequest createGetCertificateRequest() {
        return new GetCertificateRequest();
    }

    /**
     * Create an instance of {@link GetActorsRequest }
     * 
     */
    public GetActorsRequest createGetActorsRequest() {
        return new GetActorsRequest();
    }

    /**
     * Create an instance of {@link GetProxiesResponse }
     * 
     */
    public GetProxiesResponse createGetProxiesResponse() {
        return new GetProxiesResponse();
    }

    /**
     * Create an instance of {@link GetManagementObjectResponse }
     * 
     */
    public GetManagementObjectResponse createGetManagementObjectResponse() {
        return new GetManagementObjectResponse();
    }

    /**
     * Create an instance of {@link GetActorsFromDatabaseRequest }
     * 
     */
    public GetActorsFromDatabaseRequest createGetActorsFromDatabaseRequest() {
        return new GetActorsFromDatabaseRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link GetActorsResponse }
     * 
     */
    public GetActorsResponse createGetActorsResponse() {
        return new GetActorsResponse();
    }

    /**
     * Create an instance of {@link GetUsersRequest }
     * 
     */
    public GetUsersRequest createGetUsersRequest() {
        return new GetUsersRequest();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link GetActorsFromDatabaseResponse }
     * 
     */
    public GetActorsFromDatabaseResponse createGetActorsFromDatabaseResponse() {
        return new GetActorsFromDatabaseResponse();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link SetUserPasswordResponse }
     * 
     */
    public SetUserPasswordResponse createSetUserPasswordResponse() {
        return new SetUserPasswordResponse();
    }

    /**
     * Create an instance of {@link GetUnitRequest }
     * 
     */
    public GetUnitRequest createGetUnitRequest() {
        return new GetUnitRequest();
    }

    /**
     * Create an instance of {@link GetPluginResponse }
     * 
     */
    public GetPluginResponse createGetPluginResponse() {
        return new GetPluginResponse();
    }

    /**
     * Create an instance of {@link GetInventoryResponse }
     * 
     */
    public GetInventoryResponse createGetInventoryResponse() {
        return new GetInventoryResponse();
    }

    /**
     * Create an instance of {@link GetPluginsResponse }
     * 
     */
    public GetPluginsResponse createGetPluginsResponse() {
        return new GetPluginsResponse();
    }

    /**
     * Create an instance of {@link GetProxiesRequest }
     * 
     */
    public GetProxiesRequest createGetProxiesRequest() {
        return new GetProxiesRequest();
    }

    /**
     * Create an instance of {@link GetCertificateResponse }
     * 
     */
    public GetCertificateResponse createGetCertificateResponse() {
        return new GetCertificateResponse();
    }

    /**
     * Create an instance of {@link GetPluginsRequest }
     * 
     */
    public GetPluginsRequest createGetPluginsRequest() {
        return new GetPluginsRequest();
    }

    /**
     * Create an instance of {@link GetManagementObjectRequest }
     * 
     */
    public GetManagementObjectRequest createGetManagementObjectRequest() {
        return new GetManagementObjectRequest();
    }

}
