//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.08 at 05:33:55 PM AST 
//


package orca.boot.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for edges complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="edges">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="edge" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="from" type="{http://issg.cs.duke.edu/sharp/boot}vertex"/>
 *                   &lt;element name="to" type="{http://issg.cs.duke.edu/sharp/boot}vertex"/>
 *                   &lt;element name="rset" type="{http://issg.cs.duke.edu/sharp/boot}rset" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "edges", propOrder = {
    "edge"
})
public class Edges {

    @XmlElement(required = true)
    protected List<Edges.Edge> edge;

    /**
     * Gets the value of the edge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Edges.Edge }
     * 
     * 
     */
    public List<Edges.Edge> getEdge() {
        if (edge == null) {
            edge = new ArrayList<Edges.Edge>();
        }
        return this.edge;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="from" type="{http://issg.cs.duke.edu/sharp/boot}vertex"/>
     *         &lt;element name="to" type="{http://issg.cs.duke.edu/sharp/boot}vertex"/>
     *         &lt;element name="rset" type="{http://issg.cs.duke.edu/sharp/boot}rset" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "from",
        "to",
        "rset"
    })
    public static class Edge {

        @XmlElement(required = true)
        protected Vertex from;
        @XmlElement(required = true)
        protected Vertex to;
        protected List<Rset> rset;

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link Vertex }
         *     
         */
        public Vertex getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link Vertex }
         *     
         */
        public void setFrom(Vertex value) {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link Vertex }
         *     
         */
        public Vertex getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link Vertex }
         *     
         */
        public void setTo(Vertex value) {
            this.to = value;
        }

        /**
         * Gets the value of the rset property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rset property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRset().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rset }
         * 
         * 
         */
        public List<Rset> getRset() {
            if (rset == null) {
                rset = new ArrayList<Rset>();
            }
            return this.rset;
        }

    }

}
